import type { AppProps } from "next/app";
import Head from "next/head";
import Navbar from "@components/atoms/Navbar";
import { createGlobalStyle } from "styled-components";
import NextImage from "next/image";
import styled from "styled-components";

const ImageContainer = styled.div`
  position: relative;
  display: flex;
  justify-content: center;
  height: 30vh;
  min-height: 11rem;
`;

const Image = styled(NextImage)`
  max-width: 100% !important;
  width: unset !important;
  min-width: unset !important;
`;

const GlobalStyle = createGlobalStyle`
  :root {
    @media (prefers-color-scheme: dark) {
      --initialBackgroundColor: #485461;
      --finalBackgroundColor: #28313b;

      --fontColor: #00ff00;
      --lineColor: #9e9e9e;
    }
    
    @media (prefers-color-scheme: light) {
      --initialBackgroundColor: #06beb6;
      --finalBackgroundColor: #48b1bf;
      
      --fontColor: #080808;
      --lineColor: #00ff00;
    }
  }

  body {
    font-family: monospace;
    min-height: 100vh;
    margin: 0px;
    background: linear-gradient(315deg, var(--initialBackgroundColor) 0%, var(--finalBackgroundColor) 74%);
    margin-inline: 2rem;
    color: var(--fontColor);
  }
`;

const shimmer = (w: string, h: string) => `
<svg width="${w}" height="${h}" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <linearGradient id="g">
      <stop stop-color="#333" offset="20%" />
      <stop stop-color="#222" offset="50%" />
      <stop stop-color="#333" offset="70%" />
    </linearGradient>
  </defs>
  <rect width="${w}" height="${h}" fill="#333" />
  <rect id="r" width="${w}" height="${h}" fill="url(#g)" />
  <animate xlink:href="#r" attributeName="x" from="-${w}" to="${w}" dur="1s" repeatCount="indefinite"  />
</svg>`;

const toBase64 = (str: string) =>
  typeof window === "undefined"
    ? Buffer.from(str).toString("base64")
    : window.btoa(str);

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Alan Marino Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, viewport-fit=cover"
        />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <Navbar />
      <main>
        <ImageContainer>
          <Image
            src="/profile-img.webp"
            alt="Picture of the author"
            placeholder="blur"
            blurDataURL={`data:image/svg+xml;base64,${toBase64(
              shimmer("40%", "40%")
            )}`}
            layout="fill"
            objectFit="contain"
            priority
          />
        </ImageContainer>
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default MyApp;
